title: Eric Cupples
description: Aerospace Engineering Student
site_title: 'Eric Cupples - Portfolio'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: Eric-Cupples
blog_url: https://www.nagekar.com
email: ericcupples@gmail.com
keybase_username: Eric_Cupples928
twitter_username: Eric_Cupples928 
reddit_username: Eric_Cupples928

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 